map:
    file_path: /home/giacomo/thai_ws/src/nav_map/excel_map/B5_envMap.csv
    width: 200
    height: 200
    resolution: 0.1
    frame_id: map
    safety_cells: 1
    
map_transform: 
    child_frame: base_footprint
    position:
        x: 0.0
        y: 0.0
        z: 0.0
    orientation:
        roll: 0.0
        pitch: 0.0
        yaw: 0.0

    
